### ISSUE TITLE
404 on accessibility feedback link?

### ISSUE THREAD

**Issue by beep** [ericwbailey/ericwbailey.design#1]
## Expected behavior

When selecting the Accessibility Feedback link, I would expect to land at https://ericwbailey.design/accessibility-statement.html#accessibility-issues.

## Actual behavior

When I selected the Accessibility Feedback link, I was directed to https://ericwbailey.design/writing/accessibility-statement.html#accessibility-issues, which doesn’t exist.

## Steps to reproduce behavior

On https://ericwbailey.design/writing/2019-05-14-lighthouse.html, I selected the “Accessibility Feedback” link, which led to the 404 noted above.

**Comment by ericwbailey** [comment]
Yikes, that's not good. I think I've fixed the issue, mind confirming? https://ericwbailey.design/accessibility-statement.html#accessibility-issues

**Comment by beep** [comment]
Confirmed! Works a real treat now; thanks, Eric!

**Comment by ericwbailey** [comment]
Thank you!
