### ISSUE TITLE
RSS feed link is broken

### ISSUE THREAD

**Issue by petergoes** [ericwbailey/ericwbailey.design#121]
## Summary

1. Go to ericwbailey.design,
2. Scroll all the way down to the footer area,
3. Click on RSS feed

### Expected result

To land on an atom feed of the blogpost

### Actual result

I ended up here: https://ericwbailey.design/writing/feed/feed.xml
Which states: The page you’re looking for can’t be found

### Additional Information

1. What device were you using: laptop and phone
2. Operating System version: macOS / Android
3. Browser(s) and version(s): Brave (1.23.75)

### Additional Information

In your source code I found the feed template. And from it, I was able to find the URL to the feed.json. It seems that only the link in the footer is wrong.

**Comment by ericwbailey** [comment]
Hey @petergoes! Thanks for the great issue report. I think I've fixed it in #122, will close if you can confirm on your end.

**Comment by petergoes** [comment]
👍 LGTM!
