### ISSUE TITLE
Opacity on document losing focus is a usability issue

### ISSUE THREAD

**Issue by jennings** [ericwbailey/ericwbailey.design#166]
I think blurring the page when the document isn't focused creates a usability issue: https://github.com/ericwbailey/ericwbailey.design/blob/af44e0775eda4a77d8df206e016cee637a8e1f2c/source/js/main.js#L22-L33

Although it's a fun trick, it assumes the page is not being read when the browser is in the background.

I keep the browser window open and visible, but I switch to other software as necessary. I expect to still be able to read and scroll the page while the browser is in the background. But, this `.js-is-blurred` class needlessly prevents me from reading the page without bringing the web browser to the foreground.

**Comment by ericwbailey** [comment]
@jennings Thanks for reporting this. I've been waffling on if it's too gimmicky, so this tells me it is. I'll get a fix out soon.

**Comment by ericwbailey** [comment]
Removed! Thank you again for this.

**Comment by jennings** [comment]
Thank you! I'm glad you mentioned that because I was worried that opening an issue against somebody's blog was bad form.

**Comment by ericwbailey** [comment]
No way, thank you for reporting it! This repo is public for a reason, and I appreciate you taking the time and effort to let me know.
