### ISSUE TITLE
Is the link to Ubersleep going to the correct page?

### ISSUE THREAD

**Issue by injms** [ericwbailey/ericwbailey.design#2]
I think that the link to Ubersleep is not correct.

## Expected behavior
Visit a page about layout, design, and typography. 

## Actual behavior
Visited page about "Best ways to know if the appliances you are buying re environmentally friendly or not"

## Steps to reproduce behavior

1. Visit https://ericwbailey.design
2. Scoll down to grey section about side projects
3. Click on "Ubersleep" link

**Comment by ericwbailey** [comment]
Oh wow, thank you! I think it should be set now.
