### ISSUE TITLE
RSS feed appears invalid

### ISSUE THREAD

**Issue by binyamin** [ericwbailey/ericwbailey.design#88]
See <https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fericwbailey.design%2Ffeed%2Ffeed.xml>, that the url does not validate. It seems to be because of an extra line at the top of the file.

![screenshot](https://user-images.githubusercontent.com/39805353/111713563-499b9580-8826-11eb-8306-5482bbc478dd.png)

**Comment by ericwbailey** [comment]
Hey @binyamin. Thanks for reporting this. I've been slammed with client work, so it might take a bit to get to this. I appreciate you subscribing, however.

**Comment by ericwbailey** [comment]
Think I got it: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fericwbailey.design%2Ffeed%2Ffeed.xml
